/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterTypeRouteImport } from './routes/register-type'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginTypeRouteImport } from './routes/login-type'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as AdvertiserNewListingRouteImport } from './routes/advertiser/new-listing'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTypeRoute = RegisterTypeRouteImport.update({
  id: '/register-type',
  path: '/register-type',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTypeRoute = LoginTypeRouteImport.update({
  id: '/login-type',
  path: '/login-type',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserNewListingRoute = AdvertiserNewListingRouteImport.update({
  id: '/advertiser/new-listing',
  path: '/advertiser/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/login-type': typeof LoginTypeRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-type': typeof RegisterTypeRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/advertiser/new-listing': typeof AdvertiserNewListingRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/login-type': typeof LoginTypeRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-type': typeof RegisterTypeRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/advertiser/new-listing': typeof AdvertiserNewListingRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/login-type': typeof LoginTypeRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-type': typeof RegisterTypeRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/verify-email': typeof VerifyEmailRoute
  '/advertiser/new-listing': typeof AdvertiserNewListingRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/dashboard'
    | '/favorites'
    | '/investors'
    | '/login'
    | '/login-type'
    | '/more'
    | '/notifications'
    | '/pricing'
    | '/privacy-policy'
    | '/register-type'
    | '/signup'
    | '/stats'
    | '/terms-of-use'
    | '/verify-email'
    | '/advertiser/new-listing'
    | '/projects/$id'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/dashboard'
    | '/favorites'
    | '/investors'
    | '/login'
    | '/login-type'
    | '/more'
    | '/notifications'
    | '/pricing'
    | '/privacy-policy'
    | '/register-type'
    | '/signup'
    | '/stats'
    | '/terms-of-use'
    | '/verify-email'
    | '/advertiser/new-listing'
    | '/projects/$id'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/categories'
    | '/dashboard'
    | '/favorites'
    | '/investors'
    | '/login'
    | '/login-type'
    | '/more'
    | '/notifications'
    | '/pricing'
    | '/privacy-policy'
    | '/register-type'
    | '/signup'
    | '/stats'
    | '/terms-of-use'
    | '/verify-email'
    | '/advertiser/new-listing'
    | '/projects/$id'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRoute
  LoginTypeRoute: typeof LoginTypeRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterTypeRoute: typeof RegisterTypeRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdvertiserNewListingRoute: typeof AdvertiserNewListingRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-type': {
      id: '/register-type'
      path: '/register-type'
      fullPath: '/register-type'
      preLoaderRoute: typeof RegisterTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-type': {
      id: '/login-type'
      path: '/login-type'
      fullPath: '/login-type'
      preLoaderRoute: typeof LoginTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser/new-listing': {
      id: '/advertiser/new-listing'
      path: '/advertiser/new-listing'
      fullPath: '/advertiser/new-listing'
      preLoaderRoute: typeof AdvertiserNewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRoute,
  LoginTypeRoute: LoginTypeRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterTypeRoute: RegisterTypeRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdvertiserNewListingRoute: AdvertiserNewListingRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
